# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            craig.
tagline:          recovering brazilophile | elearning jockey
description:      recovering brazilophile | elearning jockey | learning technologist | afrofuturist
url:              http://craigwiggins.github.io
baseurl:          /

author:
  name:           'Craig Wiggins'
  url:            https://twitter.com/oxala75

paginate:         3

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/craigwiggins/craigwiggins.github.io
